import './styles/form.css';
import './styles/sections.css';
import './styles/offer.css';
import './styles/faq.css';
import './styles/modal.css';
import './styles/responsive.css';
import { initMarquee } from './modules/marquee.js';
import { initAccordions } from './modules/accordions.js';
import { initOffer } from './modules/offer.js';
import { initPeruModal } from './modules/peru-modal.js';
import { initTracking } from './modules/tracking.js';
import { initReveal } from './modules/reveal.js';
import { initTrialFormPresentation } from './modules/trial-form.js';
import { initHeader } from './modules/header.js';
import { initTestimonials } from './modules/testimonials.js';
import './styles/testimonials.css';
import { removeLegacyBlocks } from './modules/remove-legacy-blocks.js';
import { initWhatsappCommunity } from './modules/whatsapp-community.js';
import './styles/whatsapp-community.css';
import { initFooter } from './modules/footer.js';
import './styles/footer.css';
import { initHeroVideo } from './modules/hero-video.js';

document.addEventListener('DOMContentLoaded', () => {
  initHeroVideo();
  initHeader();
  removeLegacyBlocks();
  initTrialFormPresentation();
  initMarquee();
  initAccordions();
  initTestimonials();
  initWhatsappCommunity();
  initFooter();
  initOffer();
  initPeruModal();
  initTracking();
  initReveal();
});
